version: '3'

services:
    site:
        build: .
        restart: always
        expose:
         - "80"
        networks:
         - proxy
         - default
        labels:
         - "traefik.backend=personality"
         - "traefik.docker.network=proxy"
         - "traefik.basic.frontend.rule=Host:colorme.solderneer.me"
         - "traefik.enable=true"
         - "traefik.basic.port=80"

networks:
    proxy:
        external: true
